# Generate Homographic Matrix

# With image and video

In [3]:
import cv2
import numpy as np

# Global variables
video_coords = []
image_coords = []
mode = "video"  # Start in video mode
video_file = 0
image_file = "/Users/xs496-jassin/Desktop/Surveillance/cafeteria2.jpg"
video_output = "video_coords.txt"
image_output = "image_coords.txt"
homography_output = "homography_matrix.txt"
h_matrix = None

def save_coords_to_file(filename, coords):
    """Save coordinates to a file."""
    with open(filename, "w") as file:
        for x, y in coords:
            file.write(f"{x}, {y}\n")
    print(f"Coordinates saved to {filename}")

def save_homography_to_file(filename, matrix):
    """Save homography matrix to a file."""
    with open(filename, "w") as file:
        for row in matrix:
            file.write(" ".join(map(str, row)) + "\n")
    print(f"Homography matrix saved to {filename}")

def click_event(event, x, y, flags, param):
    """Handle mouse click events to capture coordinates."""
    global video_coords, image_coords, mode

    if event == cv2.EVENT_LBUTTONDOWN:
        if mode == "video":
            video_coords.append((x, y))
            print(f"Video coordinates: {x}, {y}")
        elif mode == "image":
            image_coords.append((x, y))
            print(f"Image coordinates: {x}, {y}")

def compute_homography():
    """Compute the homography matrix from video to image."""
    global h_matrix
    if len(video_coords) >= 4 and len(image_coords) >= 4:
        video_pts = np.array(video_coords, dtype=np.float32)
        image_pts = np.array(image_coords, dtype=np.float32)
        h_matrix, _ = cv2.findHomography(video_pts, image_pts)
        print("Homography matrix computed:")
        print(h_matrix)
    else:
        print("Need at least 4 points in both video and image to compute homography.")

def main():
    global mode
    # Load video and image
    video = cv2.VideoCapture(video_file)
    image = cv2.imread(image_file)

    while True:
        if mode == "video":
            ret, frame = video.read()
            if not ret:
                print("End of video or unable to load video.")
                break
            cv2.imshow("Frame", frame)
        else:  # mode == "image"
            cv2.imshow("Frame", image)

        cv2.setMouseCallback("Frame", click_event)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('s'):  # Switch mode
            mode = "image" if mode == "video" else "video"
            print(f"Switched to {mode} mode.")
        elif key == ord('q'):  # Quit
            break
        elif key == ord('c'):  # Compute homography matrix
            compute_homography()
        elif key == ord('v'):  # Save video coordinates
            save_coords_to_file(video_output, video_coords)
        elif key == ord('i'):  # Save image coordinates
            save_coords_to_file(image_output, image_coords)
        elif key == ord('h'):  # Save homography matrix
            if h_matrix is not None:
                save_homography_to_file(homography_output, h_matrix)
            else:
                print("Homography matrix not computed yet. Press 'c' to compute.")

    video.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()


End of video or unable to load video.


: 

# With Image 1 and Image 2

In [1]:
import cv2
import numpy as np

# Global variables
image1_coords = []
image2_coords = []
mode = "image1"  # Start in image1 mode
image1_file = "/Users/xs496-jassin/Desktop/Surveillance/640sizecv2.png"  # Image 1 file path
image2_file = "/Users/xs496-jassin/Desktop/Surveillance/grid.jpg"  # Image 2 file path
image1_output = "image1_coords.txt"
image2_output = "image2_coords.txt"
homography_output = "homography_matrix.txt"
h_matrix = None

def save_coords_to_file(filename, coords):
    """Save coordinates to a file."""
    with open(filename, "w") as file:
        for x, y in coords:
            file.write(f"{x}, {y}\n")
    print(f"Coordinates saved to {filename}")

def save_homography_to_file(filename, matrix):
    """Save homography matrix to a file."""
    with open(filename, "w") as file:
        for row in matrix:
            file.write(" ".join(map(str, row)) + "\n")
    print(f"Homography matrix saved to {filename}")

def click_event(event, x, y, flags, param):
    """Handle mouse click events to capture coordinates."""
    global image1_coords, image2_coords, mode

    if event == cv2.EVENT_LBUTTONDOWN:
        if mode == "image1":
            image1_coords.append((x, y))
            print(f"Image 1 coordinates: {x}, {y}")
        elif mode == "image2":
            image2_coords.append((x, y))
            print(f"Image 2 coordinates: {x}, {y}")

def compute_homography():
    """Compute the homography matrix from image1 to image2."""
    global h_matrix
    if len(image1_coords) >= 4 and len(image2_coords) >= 4:
        image1_pts = np.array(image1_coords, dtype=np.float32)
        image2_pts = np.array(image2_coords, dtype=np.float32)
        h_matrix, _ = cv2.findHomography(image1_pts, image2_pts)
        print("Homography matrix computed:")
        print(h_matrix)
    else:
        print("Need at least 4 points in both images to compute homography.")

def main():
    global mode
    # Load both images
    image1 = cv2.imread(image1_file)
    image2 = cv2.imread(image2_file)

    while True:
        if mode == "image1":
            cv2.imshow("Frame", image1)
        elif mode == "image2":
            cv2.imshow("Frame", image2)

        cv2.setMouseCallback("Frame", click_event)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('s'):  # Switch mode between image1 and image2
            mode = "image2" if mode == "image1" else "image1"
            print(f"Switched to {mode} mode.")
        elif key == ord('q'):  # Quit
            break
        elif key == ord('c'):  # Compute homography matrix
            compute_homography()
        elif key == ord('i'):  # Save image1 coordinates
            save_coords_to_file(image1_output, image1_coords)
        elif key == ord('j'):  # Save image2 coordinates
            save_coords_to_file(image2_output, image2_coords)
        elif key == ord('h'):  # Save homography matrix
            if h_matrix is not None:
                save_homography_to_file(homography_output, h_matrix)
            else:
                print("Homography matrix not computed yet. Press 'c' to compute.")

    cv2.destroyAllWindows()

main()


2025-01-14 12:35:24.612 Python[19466:35648182] +[IMKClient subclass]: chose IMKClient_Legacy
2025-01-14 12:35:24.612 Python[19466:35648182] +[IMKInputSession subclass]: chose IMKInputSession_Legacy


: 

# Point Mapping

In [1]:
import cv2
import numpy as np

# Initialize global variables
h_matrix = None
image_file = "/Users/xs496-jassin/Desktop/Surveillance/room.jpg"
image = None

def transform_to_image(x, y, h_matrix):
    """Transform video coordinates to image coordinates using the homography matrix."""
    video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
    image_coords = np.dot(h_matrix, video_coords)
    image_coords /= image_coords[2]  # Normalize by z-coordinate
    return int(image_coords[0]), int(image_coords[1])

def click_event(event, x, y, flags, param):
    """Handle mouse click events to draw a circle on the image."""
    global image, h_matrix

    if event == cv2.EVENT_LBUTTONDOWN:
        if h_matrix is None:
            print("Homography matrix is not loaded or computed. Please set it up.")
            return

        # Transform video coordinates to image coordinates
        img_x, img_y = transform_to_image(x, y, h_matrix)
        print(f"Mapped coordinates: Video({x}, {y}) -> Image({img_x}, {img_y})")

        # Draw a circle on the image
        cv2.circle(image, (img_x, img_y), 5, (0, 0, 255), -1)
        cv2.imshow("Mapped Image", image)

def main():
    global image, h_matrix

    # Load the image
    image = cv2.imread(image_file)
    if image is None:
        print("Failed to load the image. Check the image path.")
        return

    # Load homography matrix
    h_matrix = np.loadtxt("homography_matrix.txt")  # Load the previously saved homography matrix
    print("Loaded Homography Matrix:")
    print(h_matrix)

    # Open the camera
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Failed to open the camera.")
        return

    # Show the image for mapping
    cv2.imshow("Mapped Image", image)

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame from the camera.")
            break

        # Show the video stream
        cv2.imshow("Camera Feed", frame)

        # Set mouse callback only after the "Camera Feed" window is created
        cv2.setMouseCallback("Camera Feed", click_event)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):  # Quit the program
            break

    cap.release()
    cv2.destroyAllWindows()


    cv2.imshow("Mapped Image", image)  # Display the image for mapping
    cv2.setMouseCallback("Camera Feed", click_event)

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame from the camera.")
            break

        # Show the video stream
        cv2.imshow("Camera Feed", frame)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):  # Quit the program
            break

    cap.release()
    cv2.destroyAllWindows()



main()


Loaded Homography Matrix:
[[-4.79612391e-01  6.37355027e-01  7.55058868e+02]
 [-9.01731146e-04 -2.66667584e-01  4.31411733e+02]
 [-1.72981056e-04  1.42417329e-03  1.00000000e+00]]


2025-01-11 09:52:01.039 Python[92782:23134421] +[IMKClient subclass]: chose IMKClient_Legacy
2025-01-11 09:52:01.039 Python[92782:23134421] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
/var/folders/lq/b9jl13d10hq6lrw9wtvydrj40000gp/T/ipykernel_92782/3334803666.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(image_coords[0]), int(image_coords[1])


Mapped coordinates: Video(1277, 17) -> Image(190, 529)
Mapped coordinates: Video(103, 609) -> Image(591, 145)
Mapped coordinates: Video(271, 624) -> Image(555, 143)
Mapped coordinates: Video(510, 633) -> Image(504, 144)
Mapped coordinates: Video(673, 658) -> Image(467, 140)
Mapped coordinates: Video(1150, 669) -> Image(359, 143)
Mapped coordinates: Video(1470, 670) -> Image(280, 147)
Mapped coordinates: Video(1618, 668) -> Image(242, 150)
Mapped coordinates: Video(529, 916) -> Image(490, 84)
Mapped coordinates: Video(786, 929) -> Image(443, 83)
Mapped coordinates: Video(1139, 936) -> Image(377, 84)
Mapped coordinates: Video(1517, 916) -> Image(299, 90)
Mapped coordinates: Video(1657, 589) -> Image(216, 175)
Mapped coordinates: Video(1704, 641) -> Image(214, 160)
Mapped coordinates: Video(1749, 710) -> Image(215, 140)
Mapped coordinates: Video(1802, 767) -> Image(213, 126)
Mapped coordinates: Video(1847, 829) -> Image(213, 112)
Mapped coordinates: Video(1891, 885) -> Image(213, 100)
Fai

: 

# Dotted tracking

In [1]:
import cv2
import numpy as np

# Initialize global variables
h_matrix = None
image_file = "/Users/xs496-jassin/Desktop/Surveillance/room.jpg"
image = None
trajectory_points = []  # List to store trajectory points on the image

def transform_to_image(x, y, h_matrix):
    """Transform video coordinates to image coordinates using the homography matrix."""
    video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
    image_coords = np.dot(h_matrix, video_coords)
    image_coords /= image_coords[2]  # Normalize by z-coordinate
    return int(image_coords[0]), int(image_coords[1])

def draw_dashed_curve(image, points, dash_length=10, gap_length=5):
    """Draw a dashed curve connecting the trajectory points."""
    for i in range(1, len(points)):
        start_point = points[i - 1]
        end_point = points[i]

        # Compute the Euclidean distance between two points
        distance = int(np.linalg.norm(np.array(end_point) - np.array(start_point)))

        # Compute the number of dashes and gaps
        dashes = distance // (dash_length + gap_length)
        for j in range(dashes):
            # Compute start and end of each dash
            fraction_start = j * (dash_length + gap_length) / distance
            fraction_end = (j * (dash_length + gap_length) + dash_length) / distance
            pt1 = (
                int(start_point[0] + fraction_start * (end_point[0] - start_point[0])),
                int(start_point[1] + fraction_start * (end_point[1] - start_point[1])),
            )
            pt2 = (
                int(start_point[0] + fraction_end * (end_point[0] - start_point[0])),
                int(start_point[1] + fraction_end * (end_point[1] - start_point[1])),
            )
            # Draw the dash
            cv2.line(image, pt1, pt2, (0, 0, 255), 2)

def click_event(event, x, y, flags, param):
    """Handle mouse click events to update trajectory and draw on the image."""
    global trajectory_points, image, h_matrix

    if event == cv2.EVENT_LBUTTONDOWN:
        if h_matrix is None:
            print("Homography matrix is not loaded or computed. Please set it up.")
            return

        # Transform video coordinates to image coordinates
        img_x, img_y = transform_to_image(x, y, h_matrix)
        print(f"Mapped coordinates: Video({x}, {y}) -> Image({img_x}, {img_y})")

        # Add the new point to the trajectory
        trajectory_points.append((img_x, img_y))

        # Clear and redraw the trajectory with dashed lines
        temp_image = image.copy()
        draw_dashed_curve(temp_image, trajectory_points)
        cv2.imshow("Mapped Image", temp_image)

def main():
    global image, h_matrix

    # Load the image
    image = cv2.imread(image_file)
    if image is None:
        print("Failed to load the image. Check the image path.")
        return

    # Load homography matrix
    h_matrix = np.loadtxt("homography_matrix.txt")  # Load the previously saved homography matrix
    print("Loaded Homography Matrix:")
    print(h_matrix)

    # Open the camera
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Failed to open the camera.")
        return

    # Show the image for mapping
    cv2.imshow("Mapped Image", image)

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame from the camera.")
            break

        # Show the video stream
        cv2.imshow("Camera Feed", frame)

        # Set mouse callback only after the "Camera Feed" window is created
        cv2.setMouseCallback("Camera Feed", click_event)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):  # Quit the program
            break

    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()


Loaded Homography Matrix:
[[-4.79612391e-01  6.37355027e-01  7.55058868e+02]
 [-9.01731146e-04 -2.66667584e-01  4.31411733e+02]
 [-1.72981056e-04  1.42417329e-03  1.00000000e+00]]


2025-01-11 10:01:30.044 Python[1299:23161632] +[IMKClient subclass]: chose IMKClient_Legacy
2025-01-11 10:01:30.044 Python[1299:23161632] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
/var/folders/lq/b9jl13d10hq6lrw9wtvydrj40000gp/T/ipykernel_1299/1239025518.py:15: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(image_coords[0]), int(image_coords[1])


Mapped coordinates: Video(219, 367) -> Image(595, 224)
Mapped coordinates: Video(184, 438) -> Image(594, 197)
Mapped coordinates: Video(160, 489) -> Image(593, 180)
Mapped coordinates: Video(171, 559) -> Image(582, 159)
Mapped coordinates: Video(263, 607) -> Image(558, 148)
Mapped coordinates: Video(373, 600) -> Image(535, 151)
Mapped coordinates: Video(540, 596) -> Image(498, 154)
Mapped coordinates: Video(690, 582) -> Image(465, 161)
Mapped coordinates: Video(826, 577) -> Image(432, 164)
Mapped coordinates: Video(968, 566) -> Image(397, 170)
Mapped coordinates: Video(1108, 559) -> Image(361, 175)
Mapped coordinates: Video(1243, 554) -> Image(325, 179)
Mapped coordinates: Video(1498, 541) -> Image(252, 189)
Mapped coordinates: Video(1567, 547) -> Image(233, 188)
Mapped coordinates: Video(1596, 611) -> Image(237, 167)
Mapped coordinates: Video(1605, 648) -> Image(242, 156)
Mapped coordinates: Video(1606, 708) -> Image(251, 139)
Mapped coordinates: Video(1606, 791) -> Image(264, 118)
Ma

: 

# Real Time Tracking

In [3]:
import cv2
import numpy as np
from ultralytics import YOLO

# Initialize global variables
h_matrix = None
image_file = "/Users/xs496-jassin/Desktop/Surveillance/nn.jpg"
image = None
trajectory_points = []  # List to store trajectory points on the image
threshold = 0.8  # Confidence threshold for person detection

def transform_to_image(x, y, h_matrix):
    """Transform video coordinates to image coordinates using the homography matrix."""
    video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
    image_coords = np.dot(h_matrix, video_coords)
    image_coords /= image_coords[2]  # Normalize by z-coordinate
    return int(image_coords[0]), int(image_coords[1])

def draw_trajectory(image, points, color=(0, 0, 255), thickness=2):
    """Draw a trajectory connecting the points."""
    for i in range(1, len(points)):
        cv2.line(image, points[i - 1], points[i], color, thickness)

def process_frame(frame, model, threshold):
    """Detect persons in the frame and return the bottom center of their bounding boxes."""
    results = model.predict(frame, conf=threshold, classes=0, verbose=False)  # Class 0 is 'person'
    centers = []

    for bbox in results[0].boxes.xyxy:  # Bounding box format: (x1, y1, x2, y2)
        x1, y1, x2, y2 = map(int, bbox)
        bottom_center = ((x1 + x2) // 2, y2)  # Bottom-center of the bounding box
        centers.append(bottom_center)

    return centers

def main():
    global image, h_matrix, trajectory_points

    # Load the image
    image = cv2.imread(image_file)
    if image is None:
        print("Failed to load the image. Check the image path.")
        return

    # Load homography matrix
    h_matrix = np.loadtxt("homography_matrix_grid.txt")
    print("Loaded Homography Matrix:")

    # Load YOLO model
    model = YOLO("yolov8n.pt")

    # Open the camera
    cap = cv2.VideoCapture("/Users/xs496-jassin/Desktop/Surveillance/cafe4.mov")
    if not cap.isOpened():
        print("Failed to open the camera.")
        return

    # Show the image for mapping
    cv2.imshow("Mapped Image", image)

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame from the camera.")
            break

        # Detect persons and get their bottom-center points
        centers = process_frame(frame, model, threshold)

        # Map each detected point to the image
        for center in centers:
            mapped_point = transform_to_image(center[0], center[1], h_matrix)
            trajectory_points.append(mapped_point)

        # Clear and redraw the trajectory
        temp_image = image.copy()
        draw_trajectory(temp_image, trajectory_points)

        # Resize the frames to the same height for concatenation
        frame_height, frame_width = frame.shape[:2]
        image_height, image_width = temp_image.shape[:2]

        scale = frame_height / image_height
        resized_image = cv2.resize(temp_image, (int(image_width * scale), frame_height))

        # Horizontally concatenate the video frame and the resized image
        concatenated_frame = np.hstack((frame, resized_image))

        # Display the concatenated frame
        cv2.imshow("Combined Feed", concatenated_frame)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):  # Quit the program
            break

if __name__ == "__main__":
    main()


Loaded Homography Matrix:


# Real-Time with Async

In [1]:
import cv2
import numpy as np
from ultralytics import YOLO
import threading

# Initialize global variables
h_matrix = None
image_file = "/Users/xs496-jassin/Desktop/Surveillance/nn.jpg"
image = None
trajectory_points = []  # List to store trajectory points on the image
threshold = 0.8  # Confidence threshold for person detection

class AsyncFrameCapture:
    def __init__(self, rtsp_link):
        self.rtsp_link = rtsp_link
        self.cap = cv2.VideoCapture(rtsp_link)
        self.frame = None
        self.lock = threading.Lock()
        self.condition = threading.Condition(self.lock)
        self.running = True
        self.thread = threading.Thread(target=self._capture_frames, daemon=True)
        self.thread.start()

    def _capture_frames(self):
        while self.running:
            success, frame = self.cap.read()
            if success:
                with self.lock:
                    self.frame = frame
                    self.condition.notify_all()

    def get_frame(self):
        with self.lock:
            return self.frame

    def stop(self):
        self.running = False
        self.thread.join()
        self.cap.release()

def transform_to_image(x, y, h_matrix):
    video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
    image_coords = np.dot(h_matrix, video_coords)
    image_coords /= image_coords[2]  # Normalize by z-coordinate
    return int(image_coords[0]), int(image_coords[1])

def draw_trajectory(image, points, color=(0, 0, 255), thickness=2):
    for i in range(1, len(points)):
        cv2.line(image, points[i - 1], points[i], color, thickness)

def process_frame(frame, model, threshold, show=True):
    results = model.predict(frame, conf=threshold, classes=0, verbose=False)  # Class 0 is 'person'
    centers = []

    for bbox in results[0].boxes.xyxy:  # Bounding box format: (x1, y1, x2, y2)
        x1, y1, x2, y2 = map(int, bbox)
        bottom_center = ((x1 + x2) // 2, y2)
        centers.append(bottom_center)

        if show:
            # Draw the bounding box on the frame
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)  # Green box with thickness 2
            # Optionally, mark the bottom center point
            cv2.circle(frame, bottom_center, 5, (0, 0, 255), -1)  # Red circle

    return centers

def main():
    global image, h_matrix, trajectory_points

    # Load the image
    image = cv2.imread(image_file)
    if image is None:
        print("Failed to load the image. Check the image path.")
        return

    # Load homography matrix
    h_matrix = np.loadtxt("homography_matrix_grid.txt")
    print("Loaded Homography Matrix : ", h_matrix)

    # Load YOLO model
    model = YOLO("yolov8n.pt")

    # Open the camera
    frame_capture = AsyncFrameCapture(0)
    
    # Show the image for mapping
    # cv2.imshow("Mapped Image", image)

    while True:
        frame = frame_capture.get_frame() 
        if frame is None:
            continue

        # Detect persons and get their bottom-center points
        centers = process_frame(frame, model, threshold)

        # Map each detected point to the image
        for center in centers:
            mapped_point = transform_to_image(center[0], center[1], h_matrix)
            trajectory_points.append(mapped_point)

        # Clear and redraw the trajectory
        temp_image = image.copy()
        draw_trajectory(temp_image, trajectory_points)

        # Resize the frames to the same height for concatenation
        frame_height, frame_width = frame.shape[:2]
        image_height, image_width = temp_image.shape[:2]

        scale = frame_height / image_height
        resized_image = cv2.resize(temp_image, (int(image_width * scale), frame_height))

        # Horizontally concatenate the video frame and the resized image
        concatenated_frame = np.hstack((frame, resized_image))

        # Display the concatenated frame
        cv2.imshow("Combined Feed", concatenated_frame)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):  # Quit the program
            frame_capture.stop()
            cv2.destroyAllWindows()
            break

main()


Loaded Homography Matrix :  [[   -0.48119     0.96414      561.63]
 [   -0.29422    -0.19341      630.66]
 [-0.00038383   0.0015108           1]]


/var/folders/lq/b9jl13d10hq6lrw9wtvydrj40000gp/T/ipykernel_62184/844599863.py:45: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(image_coords[0]), int(image_coords[1])
2025-01-14 11:35:05.002 Python[62184:35468899] +[IMKClient subclass]: chose IMKClient_Legacy
2025-01-14 11:35:05.002 Python[62184:35468899] +[IMKInputSession subclass]: chose IMKInputSession_Legacy


# Without deepsort and with asyc

In [ ]:
import threading
import numpy as np
import cv2
from ultralytics import YOLO

CONFIDENCE_THRESHOLD = 0.8
WHITE = (255, 255, 255)
OUTPUT_SIZE = (640, 640)  # New size for both input and output frames

# Initialize the video capture object
video_cap = cv2.VideoCapture("cafe3.mov")

# Load the YOLOv8n model
model = YOLO("yolov8n.pt")

# Load the homography matrix
h_matrix = np.loadtxt("homography_matrix_grid.txt")
r_image = cv2.imread("nn.jpg")
if r_image is None:
    raise FileNotFoundError("Background image not found at the specified path.")
print("Loaded Homography Matrix:")

# Function to transform coordinates using the homography matrix
def transform_to_image(x, y, h_matrix):
    video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
    image_coords = np.dot(h_matrix, video_coords)
    image_coords /= image_coords[2]  # Normalize by z-coordinate
    return int(image_coords[0]), int(image_coords[1])

# AsyncFrameCapture for frame retrieval
class AsyncFrameCapture:
    def __init__(self, rtsp_link):
        self.rtsp_link = rtsp_link
        self.cap = cv2.VideoCapture(rtsp_link)
        self.frame = None
        self.lock = threading.Lock()
        self.condition = threading.Condition(self.lock)
        self.running = True
        self.thread = threading.Thread(target=self._capture_frames, daemon=True)
        self.thread.start()

    def _capture_frames(self):
        while self.running:
            success, frame = self.cap.read()
            frame = cv2.resize(frame, (640,640))
            if success:
                with self.lock:
                    self.frame = frame
                    self.condition.notify_all()

    def get_frame(self):
        with self.lock:
            return self.frame

    def stop(self):
        self.running = False
        self.thread.join()
        self.cap.release()

frame_capture = AsyncFrameCapture("/Users/xs496-jassin/Desktop/Surveillance/cafe3.mov")

while True:
    frame = frame_capture.get_frame()
    if frame is None:
        continue

    # Run the YOLO model on the frame
    detections = model.predict(frame, conf=CONFIDENCE_THRESHOLD, verbose=False)[0]

    # Prepare detection results
    for data in detections.boxes.data.tolist():
        confidence = data[4]
        class_id = int(data[5])
        if class_id != 0 or confidence < CONFIDENCE_THRESHOLD:  # Skip non-person detections
            continue

        xmin, ymin, xmax, ymax = int(data[0]), int(data[1]), int(data[2]), int(data[3])
        x, y = (xmin + xmax) // 2, ymax

        # Transform the center point to the room image
        mapped_point = transform_to_image(x, y, h_matrix)

        # Draw bounding box and center point
        color = (255,0,255)
        cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), color, 2)
        cv2.circle(frame, (x, y), 5, color, -1)

        # Draw mapped point on the room image
        cv2.circle(r_image, mapped_point, 5, color, -1)

    # Resize and display frames
    frame_resized_original = cv2.resize(r_image, OUTPUT_SIZE)
    frame_resized = cv2.resize(frame, OUTPUT_SIZE)
    stacked_frame = np.hstack((frame_resized_original, frame_resized))
    cv2.imshow("Frame Stack", stacked_frame)

    if cv2.waitKey(1) == ord("q"):
        break

frame_capture.stop()
cv2.destroyAllWindows()


Loaded Homography Matrix:


/var/folders/lq/b9jl13d10hq6lrw9wtvydrj40000gp/T/ipykernel_62184/4103489502.py:28: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(image_coords[0]), int(image_coords[1])


: 

# With DeepSORT

In [1]:
import datetime
import numpy as np
import cv2
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort

CONFIDENCE_THRESHOLD = 0.8
WHITE = (255, 255, 255)
OUTPUT_SIZE = (640, 640)  # New size for both input and output frames

# Initialize the video capture object
video_cap = cv2.VideoCapture("/Users/xs496-jassin/Desktop/Surveillance/cafe3.mov")

# Load the YOLOv8n model
model = YOLO("yolov8n.pt")
tracker = DeepSort(max_age=50)

# Load the homography matrix
h_matrix = np.loadtxt("homography_matrix_grid.txt")
r_image = cv2.imread("/Users/xs496-jassin/Desktop/Surveillance/nn.jpg")
if r_image is None:
    raise FileNotFoundError("Background image not found at the specified path.")
print("Loaded Homography Matrix:")

# Dictionary to store trajectory points for each track ID
trajectory_points = {}

# Function to draw dashed lines
def draw_dashed_line(image, start_point, end_point, color, thickness, dash_length=10):
    """Draws a dashed line between two points."""
    x1, y1 = start_point
    x2, y2 = end_point
    line_length = int(np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2))
    for i in range(0, line_length, dash_length * 2):
        start = i / line_length
        end = (i + dash_length) / line_length
        start_x = int(x1 + start * (x2 - x1))
        start_y = int(y1 + start * (y2 - y1))
        end_x = int(x1 + end * (x2 - x1))
        end_y = int(y1 + end * (y2 - y1))
        cv2.line(image, (start_x, start_y), (end_x, end_y), color, thickness)

def draw_dotted_line(image, start_point, end_point, color, radius=3):
    """Draws a line with dots between two points."""
    x1, y1 = start_point
    x2, y2 = end_point
    line_length = int(np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2))
    
    # Place dots along the line at regular intervals
    for i in range(0, line_length, radius * 4):  # Adjust spacing by modifying radius * 4
        start = i / line_length
        start_x = int(x1 + start * (x2 - x1))
        start_y = int(y1 + start * (y2 - y1))
        cv2.circle(image, (start_x, start_y), radius, color, -1)

# Function to transform coordinates using the homography matrix
def transform_to_image(x, y, h_matrix):
    video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
    image_coords = np.dot(h_matrix, video_coords)
    image_coords /= image_coords[2]  # Normalize by z-coordinate
    return int(image_coords[0]), int(image_coords[1])

# Function to generate a unique color for each track ID
def get_unique_color(track_id):
    try:
        track_id = int(track_id)  # Ensure track_id is an integer
    except ValueError:
        raise TypeError(f"Track ID must be convertible to an integer, but got {track_id}")

    np.random.seed(track_id)  # Seed the random number generator
    color = tuple(np.random.randint(0, 255, 3).tolist())
    return color

while True:
    ret, frame = video_cap.read()
    if not ret:
        break

    # Run the YOLO model on the frame
    detections = model.predict(frame, conf=CONFIDENCE_THRESHOLD, verbose=False)[0]

    # Prepare detection results
    results = []
    for data in detections.boxes.data.tolist():
        confidence = data[4]
        class_id = int(data[5])
        if class_id != 0 or confidence < CONFIDENCE_THRESHOLD:  # Skip non-person detections
            continue
        xmin, ymin, xmax, ymax = int(data[0]), int(data[1]), int(data[2]), int(data[3])
        results.append([[xmin, ymin, xmax - xmin, ymax - ymin], confidence, class_id])

    # Update the tracker
    tracks = tracker.update_tracks(results, frame=frame)

    # Draw detections and trajectories
    for track in tracks:
        if not track.is_confirmed():
            continue

        track_id = track.track_id
        ltrb = track.to_ltrb()
        xmin, ymin, xmax, ymax = int(ltrb[0]), int(ltrb[1]), int(ltrb[2]), int(ltrb[3])
        x, y = (xmin + xmax) // 2, ymax  # Bottom-center points
        # center_y = ymin + (ymax - ymin) // 2  # Center of the bounding box
        # y = (ymax + center_y) // 2  # Midpoint between the bottom and the center
        # x = (xmin + xmax) // 2  

        # Get unique color for the track
        color = get_unique_color(track_id)

        # Map the point to the room image
        mapped_point = transform_to_image(x, y, h_matrix)

        # Update the trajectory for this track
        if track_id not in trajectory_points:
            trajectory_points[track_id] = []
        trajectory_points[track_id].append(mapped_point)

        # Draw the dashed trajectory line
        points = trajectory_points[track_id]
        for i in range(1, len(points)):
            draw_dotted_line(r_image, points[i - 1], points[i], color)

        # Draw bounding box and track ID
        cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), color, 2)
        cv2.putText(frame, str(track_id), (xmin + 5, ymin - 8),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, WHITE, 2)

    # Resize images for display
    frame_resized_original = cv2.resize(r_image, OUTPUT_SIZE)
    frame_resized = cv2.resize(frame, OUTPUT_SIZE)

    # Stack frames side by side
    stacked_frame = np.hstack((frame_resized_original, frame_resized))

    # Show the stacked frames
    cv2.imshow("Frame Stack", stacked_frame)
    if cv2.waitKey(1) == ord("q"):
        break

video_cap.release()
cv2.destroyAllWindows()


Loaded Homography Matrix:


2025-01-13 20:26:53.706 Python[22828:32963192] +[IMKClient subclass]: chose IMKClient_Legacy
2025-01-13 20:26:53.706 Python[22828:32963192] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
/var/folders/lq/b9jl13d10hq6lrw9wtvydrj40000gp/T/ipykernel_22828/4015661398.py:61: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return int(image_coords[0]), int(image_coords[1])


: 

# Try Fast (with AsyncFrameCapture)

In [2]:
# import datetime
# import numpy as np
# import cv2
# import threading
# from ultralytics import YOLO
# from deep_sort_realtime.deepsort_tracker import DeepSort

# CONFIDENCE_THRESHOLD = 0.1
# WHITE = (255, 255, 255)
# OUTPUT_SIZE = (640, 640)  # New size for both input and output frames

# # Initialize the YOLO model and tracker
# model = YOLO("yolov8n.pt")
# tracker = DeepSort(max_age=50)

# # Load the homography matrix
# h_matrix = np.loadtxt("homography_matrix_cafeteria.txt")
# r_image = cv2.imread("/Users/xs496-jassin/Desktop/Surveillance/cafeteria2.jpg")
# if r_image is None:
#     raise FileNotFoundError("Background image not found at the specified path.")
# print("Loaded Homography Matrix:")

# # Initialize trajectory points dictionary
# trajectory_points = {}

# # Function to draw dashed lines
# def draw_dashed_line(image, start_point, end_point, color, thickness, dash_length=10):
#     """Draws a dashed line between two points."""
#     x1, y1 = start_point
#     x2, y2 = end_point
#     line_length = int(np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2))
#     for i in range(0, line_length, dash_length * 2):
#         start = i / line_length
#         end = (i + dash_length) / line_length
#         start_x = int(x1 + start * (x2 - x1))
#         start_y = int(y1 + start * (y2 - y1))
#         end_x = int(x1 + end * (x2 - x1))
#         end_y = int(y1 + end * (y2 - y1))
#         cv2.line(image, (start_x, start_y), (end_x, end_y), color, thickness)

# def draw_dotted_line(image, start_point, end_point, color, radius=3):
#     """Draws a line with dots between two points."""
#     x1, y1 = start_point
#     x2, y2 = end_point
#     line_length = int(np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2))
    
#     # Place dots along the line at regular intervals
#     for i in range(0, line_length, radius * 4):  # Adjust spacing by modifying radius * 4
#         start = i / line_length
#         start_x = int(x1 + start * (x2 - x1))
#         start_y = int(y1 + start * (y2 - y1))
#         cv2.circle(image, (start_x, start_y), radius, color, -1)

# # Function to transform coordinates using the homography matrix
# def transform_to_image(x, y, h_matrix):
#     video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
#     image_coords = np.dot(h_matrix, video_coords)
#     image_coords /= image_coords[2]  # Normalize by z-coordinate
#     return int(image_coords[0]), int(image_coords[1])

# # Function to generate a unique color for each track ID
# def get_unique_color(track_id):
#     try:
#         track_id = int(track_id)  # Ensure track_id is an integer
#     except ValueError:
#         raise TypeError(f"Track ID must be convertible to an integer, but got {track_id}")

#     np.random.seed(track_id)  # Seed the random number generator
#     color = tuple(np.random.randint(0, 255, 3).tolist())
#     return color

# # AsyncFrameCapture for frame retrieval
# class AsyncFrameCapture:
#     def __init__(self, rtsp_link):
#         self.rtsp_link = rtsp_link
#         self.cap = cv2.VideoCapture(rtsp_link)
#         self.frame = None
#         self.lock = threading.Lock()
#         self.condition = threading.Condition(self.lock)
#         self.running = True
#         self.thread = threading.Thread(target=self._capture_frames, daemon=True)
#         self.thread.start()

#     def _capture_frames(self):
#         while self.running:
#             success, frame = self.cap.read()
#             if success:
#                 with self.lock:
#                     self.frame = frame
#                     self.condition.notify_all()

#     def get_frame(self):
#         with self.lock:
#             return self.frame

#     def stop(self):
#         self.running = False
#         self.thread.join()
#         self.cap.release()

# # Initialize frame capture
# frame_capture = AsyncFrameCapture("/Users/xs496-jassin/Desktop/Surveillance/cafe3.mov")

# # Main processing loop
# while True:
#     # Get the latest frame
#     frame = frame_capture.get_frame()
#     if frame is None:
#         continue

#     # Run the YOLO model on the frame
#     detections = model.predict(frame, conf=CONFIDENCE_THRESHOLD, verbose=False)[0]

#     # Prepare detection results
#     results = []
#     for data in detections.boxes.data.tolist():
#         confidence = data[4]
#         class_id = int(data[5])
#         if class_id != 0 or confidence < CONFIDENCE_THRESHOLD:
#             continue
#         xmin, ymin, xmax, ymax = int(data[0]), int(data[1]), int(data[2]), int(data[3])
#         results.append([[xmin, ymin, xmax - xmin, ymax - ymin], confidence, class_id])

#     # Update the tracker
#     tracks = tracker.update_tracks(results, frame=frame)

#     # Draw detections and trajectories
#     for track in tracks:
#         if not track.is_confirmed():
#             continue

#         track_id = track.track_id
#         ltrb = track.to_ltrb()
#         xmin, ymin, xmax, ymax = int(ltrb[0]), int(ltrb[1]), int(ltrb[2]), int(ltrb[3])
#         center_y = ymin + (ymax - ymin) // 2  # Center of the bounding box
#         y = (ymax + center_y) // 2  # Midpoint between the bottom and the center
#         x = (xmin + xmax) // 2  

#         # Get unique color for the track
#         color = get_unique_color(track_id)

#         # Map the point to the room image
#         mapped_point = transform_to_image(x, y, h_matrix)

#         # Update the trajectory for this track
#         if track_id not in trajectory_points:
#             trajectory_points[track_id] = []
#         trajectory_points[track_id].append(mapped_point)

#         # Draw the dashed trajectory line
#         points = trajectory_points[track_id]
#         for i in range(1, len(points)):
#             draw_dotted_line(r_image, points[i - 1], points[i], color)

#         # Draw bounding box and track ID
#         cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), color, 2)
#         cv2.putText(frame, str(track_id), (xmin + 5, ymin - 8),
#                     cv2.FONT_HERSHEY_SIMPLEX, 0.5, WHITE, 2)

#     # Resize images for display
#     frame_resized_original = cv2.resize(r_image, OUTPUT_SIZE)
#     frame_resized = cv2.resize(frame, OUTPUT_SIZE)

#     # Stack frames side by side
#     stacked_frame = np.hstack((frame_resized_original, frame_resized))

#     # Show the stacked frames
#     cv2.imshow("Frame Stack", stacked_frame)
#     if cv2.waitKey(1) == ord("q"):
#         break

# # Stop the frame capture and clean up
# frame_capture.stop()
# cv2.destroyAllWindows()


Loaded Homography Matrix:


In [2]:
import threading
import numpy as np
import cv2
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort

CONFIDENCE_THRESHOLD = 0.8
WHITE = (255, 255, 255)
OUTPUT_SIZE = (640, 640)  # New size for both input and output frames

# Initialize the video capture object
video_cap = cv2.VideoCapture("cafe3.mov")

# Load the YOLOv8n model
model = YOLO("yolov8n.pt")
tracker = DeepSort(max_age=50)

# Load the homography matrix
h_matrix = np.loadtxt("homography_matrix_grid.txt")
r_image = cv2.imread("cafeteria2.jpg")
if r_image is None:
    raise FileNotFoundError("Background image not found at the specified path.")
print("Loaded Homography Matrix:")

# Dictionary to store trajectory points for each track ID
trajectory_points = {}

# AsyncFrameCapture for frame retrieval
class AsyncFrameCapture:
    def __init__(self, rtsp_link):
        self.rtsp_link = rtsp_link
        self.cap = cv2.VideoCapture(rtsp_link)
        self.frame = None
        self.lock = threading.Lock()
        self.condition = threading.Condition(self.lock)
        self.running = True
        self.thread = threading.Thread(target=self._capture_frames, daemon=True)
        self.thread.start()

    def _capture_frames(self):
        while self.running:
            success, frame = self.cap.read()
            if success:
                with self.lock:
                    self.frame = frame
                    self.condition.notify_all()

    def get_frame(self):
        with self.lock:
            return self.frame

    def stop(self):
        self.running = False
        self.thread.join()
        self.cap.release()

# Function to draw dashed lines
def draw_dashed_line(image, start_point, end_point, color, thickness, dash_length=10):
    """Draws a dashed line between two points."""
    x1, y1 = start_point
    x2, y2 = end_point
    line_length = int(np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2))
    for i in range(0, line_length, dash_length * 2):
        start = i / line_length
        end = (i + dash_length) / line_length
        start_x = int(x1 + start * (x2 - x1))
        start_y = int(y1 + start * (y2 - y1))
        end_x = int(x1 + end * (x2 - x1))
        end_y = int(y1 + end * (y2 - y1))
        cv2.line(image, (start_x, start_y), (end_x, end_y), color, thickness)

def draw_dotted_line(image, start_point, end_point, color, radius=3):
    """Draws a line with dots between two points."""
    x1, y1 = start_point
    x2, y2 = end_point
    line_length = int(np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2))
    
    # Place dots along the line at regular intervals
    for i in range(0, line_length, radius * 4):  # Adjust spacing by modifying radius * 4
        start = i / line_length
        start_x = int(x1 + start * (x2 - x1))
        start_y = int(y1 + start * (y2 - y1))
        cv2.circle(image, (start_x, start_y), radius, color, -1)

# Function to transform coordinates using the homography matrix
def transform_to_image(x, y, h_matrix):
    video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
    image_coords = np.dot(h_matrix, video_coords)
    image_coords /= image_coords[2]  # Normalize by z-coordinate
    return int(image_coords[0]), int(image_coords[1])

# Function to generate a unique color for each track ID
def get_unique_color(track_id):
    try:
        track_id = int(track_id)  # Ensure track_id is an integer
    except ValueError:
        raise TypeError(f"Track ID must be convertible to an integer, but got {track_id}")

    np.random.seed(track_id)  # Seed the random number generator
    color = tuple(np.random.randint(0, 255, 3).tolist())
    return color

frame_capture = AsyncFrameCapture("/Users/xs496-jassin/Desktop/Surveillance/cafe3.mov")

while True:
    frame = frame_capture.get_frame()
    if frame is None:
        continue

    # Run the YOLO model on the frame
    detections = model.predict(frame, conf=CONFIDENCE_THRESHOLD, verbose=False)[0]

    # Prepare detection results
    results = []
    for data in detections.boxes.data.tolist():
        confidence = data[4]
        class_id = int(data[5])
        if class_id != 0 or confidence < CONFIDENCE_THRESHOLD:  # Skip non-person detections
            continue
        xmin, ymin, xmax, ymax = int(data[0]), int(data[1]), int(data[2]), int(data[3])
        results.append([[xmin, ymin, xmax - xmin, ymax - ymin], confidence, class_id])

    # Update the tracker
    tracks = tracker.update_tracks(results, frame=frame)

    # Draw detections and trajectories
    for track in tracks:
        if not track.is_confirmed():
            continue

        track_id = track.track_id
        ltrb = track.to_ltrb()
        xmin, ymin, xmax, ymax = int(ltrb[0]), int(ltrb[1]), int(ltrb[2]), int(ltrb[3])
        # x, y = (xmin + xmax) // 2, ymax  # Bottom-center point
        center_y = ymin + (ymax - ymin) // 2  # Center of the bounding box
        y = (ymax + center_y) // 2  # Midpoint between the bottom and the center
        x = (xmin + xmax) // 2  

        # Get unique color for the track
        color = get_unique_color(track_id)

        # Map the point to the room image
        mapped_point = transform_to_image(x, y, h_matrix)

        # Update the trajectory for this track
        if track_id not in trajectory_points:
            trajectory_points[track_id] = []
        trajectory_points[track_id].append(mapped_point)

        # Draw the dashed trajectory line
        points = trajectory_points[track_id]
        for i in range(1, len(points)):
            draw_dotted_line(r_image, points[i - 1], points[i], color)

        # Draw bounding box and track ID
        cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), color, 2)
        cv2.putText(frame, str(track_id), (xmin + 5, ymin - 8),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, WHITE, 2)

    # Resize images for display
    frame_resized_original = cv2.resize(r_image, OUTPUT_SIZE)
    frame_resized = cv2.resize(frame, OUTPUT_SIZE)

    # Stack frames side by side
    stacked_frame = np.hstack((frame_resized_original, frame_resized))

    # Show the stacked frames
    cv2.imshow("Frame Stack", stacked_frame)
    if cv2.waitKey(1) == ord("q"):
        break

frame_capture.stop()
cv2.destroyAllWindows()


Loaded Homography Matrix:


2025-01-14 09:33:55.127 Python[87020:35223843] +[IMKClient subclass]: chose IMKClient_Legacy
2025-01-14 09:33:55.127 Python[87020:35223843] +[IMKInputSession subclass]: chose IMKInputSession_Legacy


# From ykw

In [3]:
import cv2
import numpy as np
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
import random

# Initialize global variables
h_matrix = None
image_file = "room.jpg"
image = None
threshold = 0.5  # Confidence threshold for person detection
tracker = DeepSort(max_age=30, n_init=3, max_cosine_distance=0.4, nn_budget=None)
person_colors = {}  # Dictionary to store unique colors for each tracked ID


def transform_to_image(x, y, h_matrix):
    """Transform video coordinates to image coordinates using the homography matrix."""
    video_coords = np.array([[x, y, 1]]).T  # Homogeneous coordinates
    image_coords = np.dot(h_matrix, video_coords)
    image_coords /= image_coords[2]  # Normalize by z-coordinate
    return int(image_coords[0]), int(image_coords[1])


def draw_trajectory(image, points, color=(0, 0, 255), thickness=2):
    """Draw a trajectory connecting the points."""
    for i in range(1, len(points)):
        cv2.line(image, points[i - 1], points[i], color, thickness)


def process_frame(frame, model, threshold):
    """Detect persons in the frame and return the bounding boxes and scores."""
    results = model.predict(frame, conf=threshold, classes=0)  # Class 0 is 'person'
    detections = []

    for bbox, score in zip(results[0].boxes.xyxy, results[0].boxes.conf):
        x1, y1, x2, y2 = map(int, bbox)
        detections.append(((x1, y1, x2, y2), score))

    return detections


def assign_color(tracked_id):
    """Assign a unique color to each tracked ID."""
    if tracked_id not in person_colors:
        person_colors[tracked_id] = [random.randint(0, 255) for _ in range(3)]
    return person_colors[tracked_id]


def main():
    global image, h_matrix

    # Load the image
    image = cv2.imread(image_file)
    if image is None:
        print("Failed to load the image. Check the image path.")
        return

    # Load homography matrix
    h_matrix = np.loadtxt("homography_matrix_ai_room.txt")  # Load the previously saved homography matrix
    print("Loaded Homography Matrix:")
    print(h_matrix)

    # Load YOLO model
    model = YOLO("yolov8n.pt")  # Replace with your lightweight YOLO model

    # Open the camera
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Failed to open the camera.")
        return

    # Show the image for mapping
    cv2.imshow("Mapped Image", image)

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame from the camera.")
            break

        # Detect persons and get their bounding boxes and scores
        detections = process_frame(frame, model, threshold)

        # Prepare detections for DeepSORT
        bbox_xywh = []
        confidences = []
        for bbox, score in detections:
            x1, y1, x2, y2 = bbox
            bbox_xywh.append([(x1 + x2) / 2, (y1 + y2) / 2, x2 - x1, y2 - y1])
            confidences.append(score)

        # Update tracker
        tracks = tracker.update_tracks(bbox_xywh, confidences, frame)

        # Process each track
        temp_image = image.copy()
        for track in tracks:
            if not track.is_confirmed():
                continue

            track_id = track.track_id
            bbox = track.to_ltrb()  # Convert to (x1, y1, x2, y2)
            x1, y1, x2, y2 = map(int, bbox)
            cx, cy = int((x1 + x2) / 2), int(y2)  # Bottom-center point

            # Map the tracked point to the image
            mapped_point = transform_to_image(cx, cy, h_matrix)

            # Draw the bounding box and ID on the frame
            color = assign_color(track_id)
            cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
            cv2.putText(frame, f"ID: {track_id}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

            # Draw the trajectory
            draw_trajectory(temp_image, [mapped_point], color=color, thickness=2)

        # Display the updated image and video feed
        cv2.imshow("Mapped Image", temp_image)
        cv2.imshow("Camera Feed", frame)

        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):  # Quit the program
            break

    cap.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()


Loaded Homography Matrix:
[[   -0.47961     0.63736      755.06]
 [-0.00090173    -0.26667      431.41]
 [-0.00017298   0.0014242           1]]

0: 384x640 1 person, 72.3ms
Speed: 2.5ms preprocess, 72.3ms inference, 0.9ms postprocess per image at shape (1, 3, 384, 640)


TypeError: object of type 'float' has no len()